name: RandomTP
version: 1.3
author: iTurtleDerp
load: STARTUP
database: false
main: me.iTurtleDerp.RandomTP.RandomTP
description: Allows players to teleport to a random location within 1000 blocks each direction
commands:
  randomtp:
    description: Go somewhere random!
  rtp:
    description: Alias for /randomtp